{{- if not .Values.proxy.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ligolo-ng-relay.fullname" . }}
type: Opaque
stringData:
  web-user: {{ .Values.proxy.webUser | quote }}
  web-password: {{ .Values.proxy.webPassword | quote }}
{{- end }}
